
service: api-kevinmitchell-io

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-west-2
  profile: api-kevinmitchell-io

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          method: ANY 
          path: /content
          cors: true
      - http: 
          method: ANY
          path: '/content/{proxy+}'
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dynamodb-local
